# Exported from Render on 2024-04-17T21:13:50Z
services:
- type: web
  name: myfirstproject
  runtime: node
  repo: https://github.com/mohammedzemouli/myfirstproject
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  region: frankfurt
  buildCommand: npm install
  startCommand: node server.js
version: "1"